### ISSUE TITLE
Fallback of scipy.fftpack?

### ISSUE THREAD

**Issue by danielcrane** [VolkerH/Optimal-cuFFT-dimensions-in-Python#1]
This isn't so much an issue as it is a question regarding the following:

> scipy.fftpack https://github.com/scipy/scipy/blob/master/scipy/fftpack/helper.py uses a rainbow table to be fast for small array sizes but has a fallback

May I ask what the fallback is?

**Comment by VolkerH** [comment]
I just had a look. `scipy` has seen quite a few changes in the fft code since I wrote that line in the readme. If you go back a bit in their version history you will find this:

https://github.com/scipy/scipy/blob/maintenance/1.3.x/scipy/fftpack/helper.py#L99

Hope that answers your question. Will update the Readme file.
I haven't looked in detail what they are doing now.

**Comment by danielcrane** [comment]
I see, thanks for your response!

From what I understand, fftpack works best for dimension sizes with prime factors up to 5, however cuFFT says it works for prime factors up to 7, which is a benefit of your function over scipy's I guess?

**Comment by VolkerH** [comment]
Well, calculating the permitted factors really isn't much different whether it is `(2,3,5)` or `(2,3,5,7)`. Without having looked at the current code I guess the scipy-code could easily be adapted to include the factor of 7. However, changing the FFT implementation to make efficient use  for the additional  factor might be a different story.

Using the lookup table gets the nearest in constant time for reasonable array sizes. Also my motivation was  to have this in flowdec (see this pull request https://github.com/hammerlab/flowdec/pull/18) and with my very limited tensorflow knowledge it was much easier to implement a table lookup than implementing the factorization as a tensorflow graph.
